# Generated by Django 5.1.5 on 2025-01-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_adress', models.GenericIPAddressField()),
                ('toner_black', models.IntegerField(default=100)),
                ('toner_cyan', models.IntegerField(default=100)),
                ('toner_magenta', models.IntegerField(default=100)),
                ('toner_yellow', models.IntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
