# Generated by Django 5.1.5 on 2025-01-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_rename_printers_printer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
